spring:
  application:
    name: notification-service
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:postgresql://localhost:5432/bookswap_notification_db
    username: wasiflatifhussain
    password: password
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      enable-idempotence: true
    consumer:
      services:
        swap-service:
          topic: swap.events
          group-id: notification-swap-consumers
        catalog-service:
          topic: catalog.events
          group-id: notification-catalog-consumers
      auto-offset-reset: earliest
  redis:
    host: localhost
    port: 6379
    
server:
  port: 8086


keycloak:
  introspect-url: http://localhost:8180/realms/BookSwap/protocol/openid-connect/token/introspect
  client-id: bookswap-backend
  client-secret: TnqapI5mhPPlj2v9GNmheiTPoN1xKOxI