spring:
  application:
    name: catalog-service
  datasource:
    url: jdbc:postgresql://localhost:5432/bookswap_catalog_db
    username: wasiflatifhussain
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      enable-idempotence: true
    catalog-service:
      topic: catalog.events

  output:
    ansi:
      enabled: ALWAYS

server:
  port: 8081


keycloak:
  introspect-url: http://localhost:8180/realms/BookSwap/protocol/openid-connect/token/introspect
  client-id: bookswap-backend
  client-secret: TnqapI5mhPPlj2v9GNmheiTPoN1xKOxI

outbox:
  relay:
    fixedDelayMs: 10000
