services:
  catalog-service:
    image: wasiflh/catalog-service:latest
    container_name: catalog-service
    ports:
      - "8081:8081"
    env_file: .env
    networks:
      - bookswap-net

  media-service:
    image: wasiflh/media-service:latest
    container_name: media-service
    ports:
      - "8082:8082"
    env_file: .env
    networks:
      - bookswap-net

  valuation-service:
    image: wasiflh/valuation-service:latest
    container_name: valuation-service
    ports:
      - "8083:8083"
    env_file: .env
    networks:
      - bookswap-net

  wallet-service:
    image: wasiflh/wallet-service:latest
    container_name: wallet-service
    ports:
      - "8084:8084"
    env_file: .env
    networks:
      - bookswap-net

  swap-service:
    image: wasiflh/swap-service:latest
    container_name: swap-service
    ports:
      - "8085:8085"
    env_file: .env
    depends_on:
      - catalog-service
      - wallet-service
    networks:
      - bookswap-net

  notification-service:
    image: wasiflh/notification-service:latest
    container_name: notification-service
    ports:
      - "8086:8086"
    env_file: .env
    networks:
      - bookswap-net

  email-service:
    image: wasiflh/email-service:latest
    container_name: email-service
    ports:
      - "8087:8087"
    env_file: .env
    networks:
      - bookswap-net

  backend-for-frontend:
    image: wasiflh/backend-for-frontend:latest
    container_name: backend-for-frontend
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - catalog-service
      - media-service
      - valuation-service
      - wallet-service
      - notification-service
    networks:
      - bookswap-net

networks:
  bookswap-net:
    external: true
