spring:
  application:
    name: media-service

  output:
    ansi:
      enabled: ALWAYS

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/bookswap_media_db
    username: ${DB_USERNAME:wasiflatifhussain}
    password: ${DB_PASSWORD:password}
    hikari:
      auto-commit: false

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      enable-idempotence: true
      services:
        media-service:
          topic: media.events
    consumer:
      services:
        catalog-service:
          topic: catalog.events
          group-id: media-catalog-consumers
      auto-offset-reset: earliest

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/BookSwap}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ${AWS_REGION:ap-southeast-1}

aws:
  s3:
    bucket-name: ${S3_BUCKET_NAME}

media:
  upload:
    ttl:
      minutes: 10
    mimes: image/jpeg,image/png
  download:
    ttl:
      minutes: 30
  max:
    file:
      size:
        bytes: 5242880  # 5 MB

server:
  port: 8082