spring:
  application:
    name: valuation-service
  datasource:
    url: jdbc:postgresql://localhost:5432/bookswap_valuation_db
    username: wasiflatifhussain
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      enable-idempotence: true
      services:
        valuation-service:
          topic: valuation.events
    consumer:
      services:
        catalog-service:
          topic: catalog.events
          group-id: valuation-catalog-consumers
      auto-offset-reset: earliest

keycloak:
  introspect-url: http://localhost:8180/realms/BookSwap/protocol/openid-connect/token/introspect
  client-id: bookswap-backend
  client-secret: TnqapI5mhPPlj2v9GNmheiTPoN1xKOxI

server:
  port: 8083