spring:
  application:
    name: swap-service

  output:
    ansi:
      enabled: ALWAYS

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/bookswap_swap_db
    username: ${DB_USERNAME:wasiflatifhussain}
    password: ${DB_PASSWORD:password}
    hikari:
      auto-commit: false

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      enable-idempotence: true
      services:
        swap-service:
          topic: swap.events

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${FIREBASE_ISSUER_URI:https://securetoken.google.com/bookswap-26231}

  client-endpoints:
    catalog: ${CATALOG_SERVICE_URL:http://localhost:8081}
    wallet: ${WALLET_SERVICE_URL:http://localhost:8084}

http:
  timeoutMs: ${HTTP_TIMEOUT_MS:2000}
  maxInMemoryMb: ${MAX_IN_MEMORY_MB:16}
  
server:
  port: 8085

outbox:
  relay:
    fixedDelayMs: 10000