spring:
  application:
    name: email-service
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:postgresql://localhost:5432/bookswap_email_db
    username: wasiflatifhussain
    password: password
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      enable-idempotence: true
    consumer:
      services:
        catalog-service:
          topic: catalog.events
          group-id: email-catalog-consumers
        swap-service:
          topic: swap.events
          group-id: email-swap-consumers
      auto-offset-reset: earliest

email:
  resend:
    api-key: ${RESEND_API_KEY}
    from-address: "BookSwap <no-reply@bookswap.work>"